### PR TITLE
feature: support snowflake

### PR DESCRIPTION
**Pull request by wfxr**
Suggested usage:

```sh
export SNOWFLAKE_ACCOUNT=...
export SNOWFLAKE_USER=...
export SNOWFLAKE_PASSWORD=...
export SNOWFLAKE_DATABASE=$(git config user.name)
oomplay init snowflake
[*] 🎮 Initializing snowflake ...
[*] 💫 Resetting snowflake ...
[*] ✨ snowflake has been reset.
[*] 🟢 snowflake is ready. (4.057588307s)
```

### CODE REVIEW

**Comment by t0t07** [comment]
Can you add the suggested usage to README? Or in cmd docs if that fits better.

**Comment by wfxr** [comment]
> Can you add the suggested usage to README? Or in cmd docs if that fits better.

NP, will add this to readme.

**Review by jinghancc — APPROVED** [review]
LGTM

**Review by t0t07 — APPROVED** [review]
lgtm!

**Pull request merged**
